let inputVatly;
let inputHoahoc;
let inputSinhhoc;
inputVatly = prompt("Nhap diem mon Vat ly");
inputHoahoc = prompt("Nhap diem mon Hoa Hoc");
inputSinhhoc = prompt("Nhap diem mon Sinh Hoc");
let Vatly = parseInt(inputVatly);
let Hoahoc = parseInt(inputSinhhoc);
let Sinhhoc = parseInt(inputHoahoc);
let trungbinh = (Vatly + Hoahoc + Sinhhoc)/3;
document.write("Diem trung binh" + trungbinh);
